<?php
// auto-generated by sfAutoloadConfigHandler
// date: 2011/06/17 15:22:03
return array(

  // sfDoctrinePlugin_module_libs

  // sfDoctrinePlugin_lib
  'sfdoctrinecli' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/cli/sfDoctrineCli.class.php',
  'sfdoctrineconnectionlistener' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionListener.class.php',
  'sfdoctrineconnectionprofiler' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineConnectionProfiler.class.php',
  'sfdoctrinedatabase' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/database/sfDoctrineDatabase.class.php',
  'sfwebdebugpaneldoctrine' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/debug/sfWebDebugPanelDoctrine.class.php',
  'sfformdoctrine' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormDoctrine.class.php',
  'sfformfilterdoctrine' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/form/sfFormFilterDoctrine.class.php',
  'sfdoctrinecolumn' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineColumn.class.php',
  'sfdoctrineformfiltergenerator' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormFilterGenerator.class.php',
  'sfdoctrineformgenerator' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineFormGenerator.class.php',
  'sfdoctrinegenerator' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/generator/sfDoctrineGenerator.class.php',
  'swift_doctrinespool' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/mailer/Swift_DoctrineSpool.class.php',
  'sfdoctrinepager' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/pager/sfDoctrinePager.class.php',
  'sfdoctrinerecord' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecord.class.php',
  'sfdoctrinerecordi18nfilter' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/record/sfDoctrineRecordI18nFilter.class.php',
  'sfdoctrineroute' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRoute.class.php',
  'sfdoctrineroutecollection' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/routing/sfDoctrineRouteCollection.class.php',
  'sfdoctrineexception' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/sfDoctrineException.class.php',
  'sfdoctrinebasetask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBaseTask.class.php',
  'sfdoctrinebuilddbtask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildDbTask.class.php',
  'sfdoctrinebuildfilterstask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFiltersTask.class.php',
  'sfdoctrinebuildformstask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildFormsTask.class.php',
  'sfdoctrinebuildmodeltask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildModelTask.class.php',
  'sfdoctrinebuildschematask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSchemaTask.class.php',
  'sfdoctrinebuildsqltask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildSqlTask.class.php',
  'sfdoctrinebuildtask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineBuildTask.class.php',
  'sfdoctrinecleanmodelfilestask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCleanModelFilesTask.class.php',
  'sfdoctrineconfiguredatabasetask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineConfigureDatabaseTask.class.php',
  'sfdoctrinecreatemodeltables' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineCreateModelTablesTask.class.php',
  'sfdoctrinedatadumptask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataDumpTask.class.php',
  'sfdoctrinedataloadtask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDataLoadTask.class.php',
  'sfdoctrinedeletemodelfilestask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDeleteModelFilesTask.class.php',
  'sfdoctrinedqltask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDqlTask.class.php',
  'sfdoctrinedropdbtask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineDropDbTask.class.php',
  'sfdoctrinegenerateadmintask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateAdminTask.class.php',
  'sfdoctrinegeneratemigrationsdbtask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDbTask.class.php',
  'sfdoctrinegeneratemigrationsdifftask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsDiffTask.class.php',
  'sfdoctrinegeneratemigrationsmodelstask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationsModelsTask.class.php',
  'sfdoctrinegeneratemigrationtask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateMigrationTask.class.php',
  'sfdoctrinegeneratemoduleforroutetask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleForRouteTask.class.php',
  'sfdoctrinegeneratemoduletask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineGenerateModuleTask.class.php',
  'sfdoctrineinsertsqltask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineInsertSqlTask.class.php',
  'sfdoctrinemigratetask' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/task/sfDoctrineMigrateTask.class.php',
  'sftesterdoctrine' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/test/sfTesterDoctrine.class.php',
  'sfvalidatordoctrinechoice' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineChoice.class.php',
  'sfvalidatordoctrineunique' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/validator/sfValidatorDoctrineUnique.class.php',
  'sfwidgetformdoctrinechoice' => 'E:/svn/websites/testapp/trunk/symfony/lib/vendor/symfony/lib/plugins/sfDoctrinePlugin/lib/widget/sfWidgetFormDoctrineChoice.class.php',

  // project
  'baseuserformfilter' => 'E:/svn/websites/testapp/trunk/symfony/lib/filter/doctrine/base/BaseUserFormFilter.class.php',
  'baseformfilterdoctrine' => 'E:/svn/websites/testapp/trunk/symfony/lib/filter/doctrine/BaseFormFilterDoctrine.class.php',
  'userformfilter' => 'E:/svn/websites/testapp/trunk/symfony/lib/filter/doctrine/UserFormFilter.class.php',
  'baseform' => 'E:/svn/websites/testapp/trunk/symfony/lib/form/BaseForm.class.php',
  'baseuserform' => 'E:/svn/websites/testapp/trunk/symfony/lib/form/doctrine/base/BaseUserForm.class.php',
  'baseformdoctrine' => 'E:/svn/websites/testapp/trunk/symfony/lib/form/doctrine/BaseFormDoctrine.class.php',
  'userform' => 'E:/svn/websites/testapp/trunk/symfony/lib/form/doctrine/UserForm.class.php',

  // project_model
  'baseuser' => 'E:/svn/websites/testapp/trunk/symfony/lib/model/doctrine/base/BaseUser.class.php',
  'user' => 'E:/svn/websites/testapp/trunk/symfony/lib/model/doctrine/User.class.php',
  'usertable' => 'E:/svn/websites/testapp/trunk/symfony/lib/model/doctrine/UserTable.class.php',

  // application
  'myuser' => 'E:/svn/websites/testapp/trunk/symfony/apps/frontend/lib/myUser.class.php',

  // modules
);
