#!/bin/bash
BEE_PHP=""

if [ "${OSTYPE}" == "cygwin" ]; then
  BEE_PHP="`cygpath -w \`dirname $BASH_SOURCE\`/bee.php`"
/usr/bin/env php $BEE_PHP "$@"
elif [ "${OSTYPE}" == "linux-gnu" ]; then
  if [ -e "/usr/bin/bee" ]; then
        BEE_PHP="`dirname \`readlink /usr/bin/bee\``/bee.php"
  else
        BEE_PHP="`dirname $0`/bee.php"
  fi
#  BEE_PHP="`dirname \`readlink /usr/bin/bee\``/bee.php"
#/usr/bin/env php -E"include dirname(__FILE__) . '/bee.php';"
  /usr/bin/env php $BEE_PHP "$@"
fi
