<?php

/**
 * BaseFeedback
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property integer $coupon_id
 * @property string $type
 * @property string $description
 * @property integer $vote
 * @property sfGuardUser $User
 * @property Coupon $Coupon
 * 
 * @method integer     getUserId()      Returns the current record's "user_id" value
 * @method integer     getCouponId()    Returns the current record's "coupon_id" value
 * @method string      getType()        Returns the current record's "type" value
 * @method string      getDescription() Returns the current record's "description" value
 * @method integer     getVote()        Returns the current record's "vote" value
 * @method sfGuardUser getUser()        Returns the current record's "User" value
 * @method Coupon      getCoupon()      Returns the current record's "Coupon" value
 * @method Feedback    setUserId()      Sets the current record's "user_id" value
 * @method Feedback    setCouponId()    Sets the current record's "coupon_id" value
 * @method Feedback    setType()        Sets the current record's "type" value
 * @method Feedback    setDescription() Sets the current record's "description" value
 * @method Feedback    setVote()        Sets the current record's "vote" value
 * @method Feedback    setUser()        Sets the current record's "User" value
 * @method Feedback    setCoupon()      Sets the current record's "Coupon" value
 * 
 * @package    findeal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseFeedback extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('feedback');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('coupon_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('type', 'string', 32, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 32,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
        $this->hasColumn('vote', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id'));

        $this->hasOne('Coupon', array(
             'local' => 'coupon_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}