<?php

/**
 * BaseCategory
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Companies
 * @property Doctrine_Collection $CompanyCategory
 * 
 * @method string              getName()            Returns the current record's "name" value
 * @method string              getDescription()     Returns the current record's "description" value
 * @method Doctrine_Collection getCompanies()       Returns the current record's "Companies" collection
 * @method Doctrine_Collection getCompanyCategory() Returns the current record's "CompanyCategory" collection
 * @method Category            setName()            Sets the current record's "name" value
 * @method Category            setDescription()     Sets the current record's "description" value
 * @method Category            setCompanies()       Sets the current record's "Companies" collection
 * @method Category            setCompanyCategory() Sets the current record's "CompanyCategory" collection
 * 
 * @package    findeal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseCategory extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('category');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Company as Companies', array(
             'refClass' => 'CompanyCategory',
             'local' => 'category_id',
             'foreign' => 'company_id'));

        $this->hasMany('CompanyCategory', array(
             'local' => 'id',
             'foreign' => 'category_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}