<?php

/**
 * BaseFavoriteCompany
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $company_id
 * @property integer $deal_id
 * @property integer $vote
 * @property Company $Company
 * @property Deal $Deal
 * 
 * @method integer         getCompanyId()  Returns the current record's "company_id" value
 * @method integer         getDealId()     Returns the current record's "deal_id" value
 * @method integer         getVote()       Returns the current record's "vote" value
 * @method Company         getCompany()    Returns the current record's "Company" value
 * @method Deal            getDeal()       Returns the current record's "Deal" value
 * @method FavoriteCompany setCompanyId()  Sets the current record's "company_id" value
 * @method FavoriteCompany setDealId()     Sets the current record's "deal_id" value
 * @method FavoriteCompany setVote()       Sets the current record's "vote" value
 * @method FavoriteCompany setCompany()    Sets the current record's "Company" value
 * @method FavoriteCompany setDeal()       Sets the current record's "Deal" value
 * 
 * @package    findeal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseFavoriteCompany extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('favorite_company');
        $this->hasColumn('company_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('deal_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             ));
        $this->hasColumn('vote', 'integer', null, array(
             'type' => 'integer',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('Company', array(
             'local' => 'company_id',
             'foreign' => 'id'));

        $this->hasOne('Deal', array(
             'local' => 'deal_id',
             'foreign' => 'id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}