<?php

/**
 * BasesfGuardUserProfile
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $user_id
 * @property date $birthday
 * @property string $address
 * @property string $zip_code
 * @property string $country
 * @property string $nationality
 * @property string $phone_number
 * @property string $fax_number
 * @property string $website
 * @property string $validate
 * @property sfGuardUser $User
 * 
 * @method integer            getUserId()       Returns the current record's "user_id" value
 * @method date               getBirthday()     Returns the current record's "birthday" value
 * @method string             getAddress()      Returns the current record's "address" value
 * @method string             getZipCode()      Returns the current record's "zip_code" value
 * @method string             getCountry()      Returns the current record's "country" value
 * @method string             getNationality()  Returns the current record's "nationality" value
 * @method string             getPhoneNumber()  Returns the current record's "phone_number" value
 * @method string             getFaxNumber()    Returns the current record's "fax_number" value
 * @method string             getWebsite()      Returns the current record's "website" value
 * @method string             getValidate()     Returns the current record's "validate" value
 * @method sfGuardUser        getUser()         Returns the current record's "User" value
 * @method sfGuardUserProfile setUserId()       Sets the current record's "user_id" value
 * @method sfGuardUserProfile setBirthday()     Sets the current record's "birthday" value
 * @method sfGuardUserProfile setAddress()      Sets the current record's "address" value
 * @method sfGuardUserProfile setZipCode()      Sets the current record's "zip_code" value
 * @method sfGuardUserProfile setCountry()      Sets the current record's "country" value
 * @method sfGuardUserProfile setNationality()  Sets the current record's "nationality" value
 * @method sfGuardUserProfile setPhoneNumber()  Sets the current record's "phone_number" value
 * @method sfGuardUserProfile setFaxNumber()    Sets the current record's "fax_number" value
 * @method sfGuardUserProfile setWebsite()      Sets the current record's "website" value
 * @method sfGuardUserProfile setValidate()     Sets the current record's "validate" value
 * @method sfGuardUserProfile setUser()         Sets the current record's "User" value
 * 
 * @package    findeal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BasesfGuardUserProfile extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('sf_guard_user_profile');
        $this->hasColumn('user_id', 'integer', null, array(
             'type' => 'integer',
             'notnull' => true,
             'unique' => true,
             ));
        $this->hasColumn('birthday', 'date', null, array(
             'type' => 'date',
             ));
        $this->hasColumn('address', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('zip_code', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('country', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('nationality', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('phone_number', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('fax_number', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('website', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
        $this->hasColumn('validate', 'string', 255, array(
             'type' => 'string',
             'length' => 255,
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasOne('sfGuardUser as User', array(
             'local' => 'user_id',
             'foreign' => 'id',
             'onDelete' => 'CASCADE'));

        $timestampable0 = new Doctrine_Template_Timestampable();
        $this->actAs($timestampable0);
    }
}