<?php

/**
 * BaseDealType
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property string $name
 * @property string $description
 * @property Doctrine_Collection $Deals
 * 
 * @method string              getName()        Returns the current record's "name" value
 * @method string              getDescription() Returns the current record's "description" value
 * @method Doctrine_Collection getDeals()       Returns the current record's "Deals" collection
 * @method DealType            setName()        Sets the current record's "name" value
 * @method DealType            setDescription() Sets the current record's "description" value
 * @method DealType            setDeals()       Sets the current record's "Deals" collection
 * 
 * @package    findeal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7691 2011-02-04 15:43:29Z jwage $
 */
abstract class BaseDealType extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('deal_type');
        $this->hasColumn('name', 'string', 255, array(
             'type' => 'string',
             'notnull' => true,
             'length' => 255,
             ));
        $this->hasColumn('description', 'string', null, array(
             'type' => 'string',
             ));
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Deal as Deals', array(
             'local' => 'id',
             'foreign' => 'deal_type_id'));

        $timestampable0 = new Doctrine_Template_Timestampable(array(
             ));
        $this->actAs($timestampable0);
    }
}