<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version2 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('user', 'test', 'string', '255', array(
             'unique' => '1',
             'notnull' => '1',
             ));
    }

    public function down()
    {
        $this->removeColumn('user', 'test');
    }
}