<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2012/01/27 15:44:06

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=nbSymfonyPlugintest_dev',
  'username' => 'testappadmin',
  'password' => 'testpwd',
  'name' => 'doctrine',
)),);
