<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2011/06/17 15:22:03

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=localhost;dbname=testapp_dev',
  'username' => 'testappadmin',
  'password' => 'db@dm1n!',
  'name' => 'doctrine',
)),);
