<?php

/**
 * CompanyCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class CompanyCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object CompanyCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('CompanyCategory');
    }
}