<?php

/**
 * DealTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DealTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DealTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('DealType');
    }
}