<?php

/**
 * Deal
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    findeal
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class Deal extends BaseDeal
{
  public function save(Doctrine_Connection $conn = null)
  {
    if($this->isNew() && !$this->getPublishedAt()) {
      $this->setPublishedAt(date('Y-m-d H:i:s', time()));
    }

//    if($this->isNew() && !$this->getStartAt()) {
//      $now = $this->getPublishedAt() ? $this->getDateTimeObject('published_at')->format('U') : time();
//      $this->setStartAt(date('Y-m-d H:i:s', $now + 60 * sfConfig::get('app_default_deal_start_after')));
//    }
//
//    if($this->isNew() && !$this->getEndAt()) {
//      $now = $this->getStartAt() ? $this->getDateTimeObject('start_at')->format('U') : time();
//      $this->setEndAt(date('Y-m-d H:i:s', $now + 3600 * sfConfig::get('app_default_deal_duration')));
//    }

    return parent::save($conn);
  }

}