<?php

/**
 * FeedbackTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class FeedbackTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object FeedbackTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Feedback');
    }
}